### ISSUE TITLE
Support config file

### ISSUE THREAD

**Issue by h2non** [h2non/apitance#8]
Add support for reading a YAML config file manifest

`.apitance`

``` yaml
features:
   - test/features/*.feature
tags:
   - sprint1
require:
   - features/support/*.js
```
